### ISSUE TITLE
Identical external IDs error after trying to import previously exported data with specific content modeling

### ISSUE THREAD

**Issue by mjstackhouse** [kontent-ai/data-ops#82] opened 2024-10-02 16:50 UTC
### Brief bug description

When I run the import command using exported data from one environment into a new, empty one, I get the validation error, "The external IDs ''event_details'' are already used in your environment. The external IDs of types, snippets, and their elements must be unique."

### Repro steps

1. Create a content type named 'X' with an element named 'Y'.
2. Create another content type named 'X Y'.
3. Use the export command to export the data from that environment.
4. Use the import command to import that exported data into a new, empty environment.

### Expected behavior

Import command runs successfully without an identical external ID error.

### Test environment

 - macOS Sonoma 14.7
 - zsh in Visual Studio Code 1.92.0

### Additional context

I have an 'Event' type with a 'Details' Linked items element and an 'Event Details' type. The idea is that the 'Event' type has information that stays the same no matter what (ex: name, description, etc.), and the 'Event Details' items get linked inside of that 'Details' element to provide specific information that varies between different versions of that event (ex: time, location, etc.). It seems that naming the types and element that way resulted in the 'Event Details' type and the 'Details' element in the 'Event' type both having an 'event_details' external ID.

### Screenshots

![event-content-type-with-details-element](https://github.com/user-attachments/assets/4eca9872-040d-4211-8ec3-bd3ee0d84b25)
![event-details-content-type](https://github.com/user-attachments/assets/30bcda0a-99d1-48d9-b679-a069d52c0b8c)
![export](https://github.com/user-attachments/assets/da6c441f-ac43-4475-914a-1020719c9043)
![import](https://github.com/user-attachments/assets/fb93eed5-9f1a-456c-a158-87e837dd2e7c)

**Comment by IvanKiral** [comment] 2024-10-03 08:29
Hey @mjstackhouse,

Thanks for opening the issue. I have checked the code and you are right. Sadly, our external_id creation does not cover this edge case. Thank you for letting us know we will fix that :)

**Comment by IvanKiral** [comment] 2024-10-17 11:07
Hey @mjstackhouse,

Should be fixed in the new version of data-ops 2.0.0 :)

**Comment by JiriLojda** [comment] 2024-10-23 15:59
I'll close this since the issue is fixed. If you encounter any problems, feel free to reopen the issue or create a new one.

**Closed by JiriLojda** 2024-10-23 15:59 UTC
